### ISSUE TITLE
default_post_command() not called in vim_handle_input()

### ISSUE THREAD

**Issue by luis-reyes-a** [B-Y-P/4coder_vim#2]
Hello! So vim_view_input_handler() calls vim_handle_input which calls vim_function() to execute a custom command function on keystroke. The problem is that default_post_command() isn't called which causes a problem if you use word_complete since deafult_post_command() updates the view's rewrite type and so the rewrite type isn't being updated. You just gotta stick default_post_command in there somewhere after (hopefully doing so won't cause any other problems. I haven't noticed any).

**Comment by B-Y-P** [comment]
Whoops, [fixed a while ago](https://github.com/B-Y-P/4coder_vim/commit/92a6b46e8906d8ee348021e934bb40c6f36499f2#diff-652ac010c188eb0b6efe364802cb832d04dd9a56fff462bc6691ed7a61d379f8R362) but forgot to close
Thanks for bringing this up :)
